name: team8
description: "2024 GDGfs RE:ALThon"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #Status management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  #DB
  shared_preferences: ^2.1.1 #tinydb
  flutter_secure_storage: ^9.2.2 #난독화 tinydb

  #etc
  flutter_screenutil: 5.9.0 #화면 사이즈 controlling
  animate_do: ^3.3.4 #애니메이션
  audio_waveforms: ^1.2.0
  chat_gpt_sdk: ^3.1.0
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.13
  riverpod_lint: ^2.6.3
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/imgs/
    - assets/mp4/

  fonts:
    - family: SeoulNamsan
      fonts:
        - asset: assets/fonts/SeoulNamsanM.ttf
    - family: Pretendard
      fonts:
        - asset: assets/fonts/PretendardVariable.ttf